name: 'Run "fcli fod session login" command'
description: 'Run "fcli fod session login" command based on environment variables'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: fortify-ps/github-action/setup@main
      with:
        export-path: false
        fcli: action-default
    - uses: fortify-ps/github-action/run@main
      with:
        # TODO If we add functionality for generating a CIToken in the sc-sast-login
        #      action, we should clean it up here. 
        cmd: '"${FCLI_CMD}" sc-sast session logout --no-revoke-token'        
branding:
  icon: 'shield'
  color: 'blue'

