name: 'Setup Fortify Tools'
description: 'Set up Fortify tools like fcli, ScanCentral Client, FoDUploader and FortifyVulnerabilityExporter'
author: 'Fortify'
inputs:
  export-path:
    description: 'Whether to add the installed tools to the system PATH variable. Allowed values: true (default) or false'
    default: 'true'
    required: false
  fcli:
    description: 'The fcli version to install. Allowed values: skip (default value, do not install fcli), latest, or specific version number.'
    default: 'skip'
    required: false
  sc-client:
    description: 'The ScanCentral Client version to install. Allowed values: skip (default value, do not install), latest, or specific version number.'
    default: 'skip'
    required: false
  fod-uploader:
    description: 'The FoDUploader version to install. Allowed values: skip (default value, do not install), latest, or specific version number.'
    default: 'skip'
    required: false
  vuln-exporter:
    description: 'The FortifyVulnerabilityExporter version to install. Allowed values: skip (default value, do not install), latest, or specific version number.'
    default: 'skip'
    required: false
runs:
  using: node20
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'blue'

